name: itungduit
description: Aplikasi Penghitung Pengeluaran.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter:
    git: https://github.com/rcdevgames/rcdev_font.git
  cloud_firestore: ^0.14.4
  cupertino_icons: ^1.0.0
  date_format: ^1.0.9
  fancy_shimmer_image: ^1.2.0
  firebase_auth: ^0.18.4+1
  firebase_core: ^0.5.3
  flui: ^0.9.2
  get: ^3.23.1
  get_storage: ^1.3.2
  getwidget: ^1.2.4
  google_fonts: ^1.1.1
  google_sign_in: ^4.5.6
  timeago: ^2.0.29

dev_dependencies:
  flutter_launcher_name: ^0.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

flutter_launcher_name:
  name: "ItungDuit"

# run `flutter pub run flutter_launcher_name:main`
